project_id = "bxrvutconietinhrngvg"

[functions.send-sms-otp]
verify_jwt = false

[functions.verify-sms-otp]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false

[functions.send-booking-reminders]
verify_jwt = false

[functions.firebase-verify-token]
verify_jwt = false

[functions.create-wallet-topup-order]
verify_jwt = false

[functions.verify-wallet-topup]
verify_jwt = false

[functions.send-welcome-notification]
verify_jwt = false

[functions.verify-upi-payment]
verify_jwt = false

[functions.send-payment-receipt]
verify_jwt = false

[functions.send-booking-confirmation]
verify_jwt = false

[functions.send-email-otp]
verify_jwt = false

[functions.verify-email-otp]
verify_jwt = false

[functions.notify-admin-new-salon]
verify_jwt = false
