project_id = "bxrvutconietinhrngvg"

[functions.send-sms-otp]
verify_jwt = false

[functions.verify-sms-otp]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false
